---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	llm_call_generator(llm_call_generator)
	llm_call_evaluator(llm_call_evaluator)
	__end__([<p>__end__</p>]):::last
	__start__ --> llm_call_generator;
	llm_call_evaluator -. &nbsp;Accepted&nbsp; .-> __end__;
	llm_call_evaluator -. &nbsp;Rejected + Feedback&nbsp; .-> llm_call_generator;
	llm_call_generator --> llm_call_evaluator;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
